### ISSUE TITLE
'here' package not working locally

### ISSUE THREAD

**Issue by swood-ecology** [Science-for-Nature-and-People/Midwest-Agriculture-Synthesis#31]
When I use the `here` package locally it defaults to '/Users/stephen.wood/www/' when I actually have the files saved several levels down in my file structure. Help? I don't want to bring us back to the dark ages of having every comment in and out their local file structures. Should we make this an RProject? That seems to deal with local file structures well--but is it compatible with Shiny apps?

**Comment by nathanhwangbo** [comment]
I'm not fully sure I understand what you are asking, but here is some info that might help:

 * If you want to traverse further down your file structure, you can add the path to `here()`. 
eg if you want to reach '/Users/Stephen.wood/www/data/data-for-app.csv', we can use `here('data/data-for-app.csv')`
* You can see why `here()` chose the your default path using the function `dr_here()`. From the documentation, here is what it looks for:

> Is a file named .here present?
> Is this an RStudio Project? Literally, can I find a file named something like foo.Rproj?
> Is this an R package? Does it have a DESCRIPTION file?
> Is this a remake project? Does it have a file named remake.yml?
> Is this a projectile project? Does it have a file named .projectile?
> Is this a checkout from a version control system? Does it have a directory named .git or .svn? Currently, only Git and Subversion are supported. 
taken from: https://github.com/jennybc/here_here

* The idea is that all participants will have the same "default" path (in our case, the .git directory). Then any path you put into the `here` argument should still work for everyone. (in our case, 'Users/Stephen.wood/www' should be your local path to the git directory.
* An Rproject will also work here, but the reason is the same (see the second line vs the last 2 line in the quote above). Also, as far as I know, Rprojects are compatible with Shiny apps.

**Comment by swood-ecology** [comment]
I think we can close this issue. My git file structure isn't in the default path for `here` but I can comment out/in my local file structure for app development and use `here` for the final version.
